apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
############################
# base
############################
# OIDC Authservice
- ../common/oidc-authservice/base
# Dex
- ../common/dex/overlays/istio

###############
# moved to distro-kfserving
###############
# # KNative
# # calls common/knative/knative-serving/base/upstream/serving-core.yaml which contains cluster-autoscaler configmap
# - ../common/knative/knative-serving/overlays/gateways
# # this depends upon knative-event cluster-autoscaler configmap
# - ../common/knative/knative-eventing/base
# - ../common/istio-1-9/cluster-local-gateway/base

# Kubeflow namespace
- ../common/kubeflow-namespace/base
# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio-1-9/kubeflow-istio-resources/base
