apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

# KNative
# calls common/knative/knative-serving/base/upstream/serving-core.yaml which contains cluster-autoscaler configmap
- ../common/istio-1-9/cluster-local-gateway/base
- ../common/knative/knative-serving/overlays/gateways
# this depends upon knative-event cluster-autoscaler configmap
- ../common/knative/knative-eventing/base

# KFServing (minus autoscaler)
- ../apps/kfserving/upstream/overlays/kubeflow
