apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kfserving-controller-manager
  namespace: kfserving-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
