apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cert-Manager
- ../common/cert-manager/cert-manager/base
- ../common/cert-manager/kubeflow-issuer/base
# Istio
- ../common/istio-1-9/istio-crds/base
- ../common/istio-1-9/istio-namespace/base
- ../common/istio-1-9/istio-install/base
# OIDC Authservice
- ../common/oidc-authservice/base



##### causing the problem: Dex - ../common/dex/overlays/istio #####
# Dex
# - ../common/dex/overlays/istio

# KNative: is used by the KFServing official Kubeflow component.
# Optionally, you can install Knative Eventing which can be used for inference request logging:
- ../common/knative/knative-eventing/base
# Knative Serving:
- ../common/knative/knative-serving/overlays/gateways
##### problem???
- ../common/istio-1-9/cluster-local-gateway/base


# # Kubeflow namespace
# - ../common/kubeflow-namespace/base
# # Kubeflow Roles
# - ../common/kubeflow-roles/base
# # Kubeflow Istio Resources
# - ../common/istio-1-9/kubeflow-istio-resources/base
