apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
############################
# base
############################
# OIDC Authservice
- ../common/oidc-authservice/base
# Dex
- ../common/dex/overlays/istio



# KNative
# calls common/knative/knative-serving/base/upstream/serving-core.yaml which contains cluster-autoscaler configmap
# - ../common/knative/knative-serving/overlays/gateways
# this depends upon knative-event cluster-autoscaler configmap
- ../common/knative/knative-eventing/base
- ../common/istio-1-9/cluster-local-gateway/base



# Kubeflow namespace
- ../common/kubeflow-namespace/base
# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio-1-9/kubeflow-istio-resources/base

############################
# Dashboard
############################
# Kubeflow Pipelines
# errors on build with kustomize v3.2.0
- ../apps/pipeline/upstream/env/platform-agnostic-multi-user
# KFServing
# - ../apps/kfserving/upstream/overlays/kubeflow
# Katib
# - ../apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../apps/centraldashboard/upstream/overlays/istio
# Admission Webhook
- ../apps/admission-webhook/upstream/overlays/cert-manager
# Notebook Controller
- ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Jupyter Web App
- ../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ../apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
-  ../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
-  ../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- ../apps/training-operator/upstream/overlays/kubeflow
# MPI Operator
- ../apps/mpi-job/upstream/overlays/kubeflow
